name: Ensure CI is Enabled

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CI_CONNECTED: ${{ vars.CI_CONNECTED }}

jobs:
  fail_if_ci_disabled:
    runs-on: ubuntu-latest
    steps:
    - name: Check Environment variable
      run: |
        echo "The value of CI_CONNECTED is '${{ env.CI_CONNECTED }}'"
        test "${{ env.CI_CONNECTED }}" = "true" \
          || { \ 
            echo "CI is Disconnected. Set CI_CONNECTED to true in GitHub's repository environment variables" >&2; \
            echo "::error::CI is not enabled because the repositorie's CI_CONNECTED environment variable != true" \
            exit 1
          ;}