name: Ensure CI is Enabled

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fail_if_ci_disabled:
    runs-on: ubuntu-latest
    steps:
    - name: Check Environment variable
      run: |
        test "${CI_CONNECTED}" = "true" \
          || { echo "CI is Disconnected. Set CI_CONNECTED to true in GitHub's environment variables" ; false ;}