name: Ensure CI is Enabled
# This workflow allows a project to disable workflows based on a repository or
# organizational environment variable. 
#
# Create a repo or org environment variable with key CI_ENABLED and value true
# for this workflow to succeed. Another other value should cause this workflow
# to fail.
#
# https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-a-repository
#
# Example usage, assuming this workflow is local to your repository:
#
# jobs:
#   ensure_ci_enabled:
#     uses: ./.github/workflows/check-ci-enabled.yml
#
#   next_task:
#     needs: ensure_ci_enabled
#     runs-on: ubuntu-latest
#     steps:
#     - ...

on:
  workflow_dispatch:
  workflow_call:

env:
  CI_ENABLED: ${{ vars.CUSTOM_VAR_CI_ENABLED }}

jobs:
  fail_if_ci_disabled:
    runs-on: ubuntu-latest
    steps:
    - name: Check Environment variable
      run: |
        printenv | grep CI_ENABLED
        echo "The value of CI_ENABLED is '${{ env.CI_ENABLED }}'"
        test "${{ env.CI_ENABLED }}" = "true" \
          || { echo "::error::Failing because the CI_ENABLED environment variable is not set to true for repo settings"; \
            exit 1 ;}