name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Image
      run: |
        podman version
        podman build --build-arg quay_expiration=1w -t testbuild1w .
        podman build --build-arg quay_expiration=2w -t testbuild2w .
        podman build --label quay.expired-after=3w -t testbuild3w .
        podman image inspect testbuild1w | jq .[0].Labels
        podman image inspect testbuild2w | jq .[0].Labels
        podman image inspect testbuild3w | jq .[0].Labels
