name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Image
      run: |
        podman version
        podman build --build-arg quay_expiration=1w -t testbuild .
        podman image inspect testbuild
        podman build --build-arg quay_expiration=2w -t testbuild2 .
        podman image inspect testbuild2
        podman build --label quay.expired-after=3w -t testbuild3 .
        podman image inspect testbuild3
