name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Image
      run: |
        podman version
        podman build --label quay.expires-after=never -t testbuildnever .        
        podman build --build-arg quay_expiration=1w -t testbuild1w .
        podman build --build-arg quay_expiration=2w -t testbuild2w .

        echo never
        podman image inspect testbuildnever | jq .[0].Labels
        
        echo 1w
        podman image inspect testbuild1w | jq .[0].Labels
        
        echo 2w
        podman image inspect testbuild2w | jq .[0].Labels

  build-neverexpire:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/workflow-call-image-create.yml
      name: build neverexpire
      with:
        name: testbuild
        tag: neverexpire

  build-withexpire:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/workflow-call-image-create.yml
      name: build 1wexpire
      with:
        name: testbuild
        tag: 1w
        expires: 1w
