name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ensure_ci_enabled:
    uses: ./.github/workflows/ci-enabled.yml
    with:
      is-enabled: ${{ vars.CUSTOM_VAR_CI_ENABLED }}

  build:
    needs: ensure_ci_enabled
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Image
      run: |
        podman version
        podman build --label quay.expires-after=never -t testbuildnever .        
        podman build --build-arg quay_expiration=1w -t testbuild1w .
        podman build --build-arg quay_expiration=2w -t testbuild2w .

        echo never
        podman image inspect testbuildnever | jq .[0].Labels
        
        echo 1w
        podman image inspect testbuild1w | jq .[0].Labels
        
        echo 2w
        podman image inspect testbuild2w | jq .[0].Labels

  build-neverexpire:
    needs: ensure_ci_enabled
    uses: ./.github/workflows/workflow-call-image-create.yml
    with:
      name: testexpiration
      tag: neverexpire
    secrets: inherit

  build-withexpire:
    needs: ensure_ci_enabled
    uses: ./.github/workflows/workflow-call-image-create.yml
    with:
      name: testexpiration
      tag: 1w
      expires: 1w
    secrets: inherit
